micronaut:
  application:
    name: mnJdbcDemo

datasources:
  default:
    url: jdbc:h2:mem:DEVDB;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2

netty:
  default:
    allocator:
      max-order: 3
